### ISSUE TITLE
AWS SQS container source is panicking

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/knative-lambda-sources#34]
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.Clients.QueueLookup(0xafa800, 0xc0000900c8, 0xae7200, 0xc0000a8d00, 0xc00002a006, 0x3, 0xc0000a8d00, 0x0, 0x0, 0xc000179450)
	/go/src/sqs/main.go:165 +0x138
main.main()
	/go/src/sqs/main.go:114 +0x607
```

**Comment by a-edakin** [comment]
miss typed issue number in commit  https://github.com/triggermesh/knative-lambda-sources/pull/35/commits/b154d7945978049fedbdd42dc210135952564d40

Instead of 35 should be 34
